name: CI

on:
  push:
    branches: 
      - master
      - main
      - develop
      - 'feature/**'
  pull_request:
    branches: 
      - master
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check code structure
      run: |
        echo "Checking project structure..."
        test -f main.py || (echo "main.py not found" && exit 1)
        test -d agents || (echo "agents directory not found" && exit 1)
        test -d api || (echo "api directory not found" && exit 1)
        test -d models || (echo "models directory not found" && exit 1)
        test -d tools || (echo "tools directory not found" && exit 1)
        test -d workflows || (echo "workflows directory not found" && exit 1)
        echo "✅ Project structure validated"

    - name: Verify Python syntax
      run: |
        python -m py_compile main.py
        python -m py_compile agents/*.py
        python -m py_compile api/*.py
        python -m py_compile models/*.py
        python -m py_compile tools/*.py
        python -m py_compile workflows/*.py
        python -m py_compile utils/*.py
        echo "✅ Python syntax check passed"

    - name: Build success
      run: |
        echo "✅ Build completed successfully for Python ${{ matrix.python-version }}"
